### ISSUE TITLE
Inappropriate source code encoding handling

### ISSUE THREAD

**Issue by arsdragonfly** [dbshch/Graduation_project_selection_site#4]
When running the project for the first time on Ubuntu GNOME 16.04 the following error occurs:
`
arsdragonfly@arsdragonfly-P15SM-A-SM1-A:~/Graduation_project_selection_site$ python main.py 
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    import pyxlsx
  File "/home/arsdragonfly/Graduation_project_selection_site/pyxlsx.py", line 77
SyntaxError: Non-ASCII character '\xe5' in file /home/arsdragonfly/Graduation_project_selection_site/pyxlsx.py on line 77, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
`
This can possibly be solved by following [https://www.python.org/dev/peps/pep-0263/](url).
Hopefully this PEP can be enforce throughout the project.

**Comment by dbshch** [comment]
This program is coded in Python 3 (which is recommended officially) which is using Unicode in coding by default so that there is no need to indicate the code. The only problem may occurs in deployment is the support of Unicode of the file system. See [locale](https://en.wikipedia.org/wiki/Locale_(computer_software)) and [fstab](https://en.wikipedia.org/wiki/Fstab) for reference.
